### ISSUE TITLE
Problem with missing ddmlib method

### ISSUE THREAD

**Issue by deepanshumadan** [shazam/fork#66]
Getting this error after updating gradle to 2.9 and gradle plugin to 1.5.0

Exception in thread "DeviceExecutor-0" java.lang.NoSuchMethodError: com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;
	at com.shazam.fork.system.adb.Installer$1.run(Installer.java:53)
	at com.shazam.fork.system.adb.Installer.tryThrice(Installer.java:77)
	at com.shazam.fork.system.adb.Installer.reinstall(Installer.java:47)
	at com.shazam.fork.system.adb.Installer.prepareInstallation(Installer.java:41)
	at com.shazam.fork.runner.DeviceTestRunner.run(DeviceTestRunner.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

gradle plugin update may have brought a newer version of ddmlib that is not compatible with one used by fork?

**Comment by iordanis** [comment]
Yeah getting the same. Thanks for spotting it.

**Comment by iordanis** [comment]
It looks we need to revert the change, since ddmlib 24.5.0 causes this exception
```
Exception in thread "CatLogger-all=sw0-up-192.168.57.101:5555" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of system
	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
	at java.lang.Thread.run(Thread.java:745)
```

As far as I can tell there are no workarounds as of this point. We also have to skip 1.5.0.

**Comment by theelfismike** [comment]
@iordanis - It looks like this is the tools bug for that IllegalStateException: https://code.google.com/p/android/issues/detail?id=195998

**Comment by iordanis** [comment]
Exactly. It's fixed but not released, so hopefully it will be in the ddmlib used by plugin 2.0.0

**Comment by ericjee** [comment]
still face it with plugin 2.0.0-alpha6 and gradle 2.10 :(

**Comment by deepanshumadan** [comment]
still seeing it with plugin 2.0.0-beta2 and gradle 2.10 :(

**Comment by deepanshumadan** [comment]
@iordanis any update on this one?

**Comment by iordanis** [comment]
No updates yet, we're still locked on an older version until 2.0.0 becomes final. We will welcome any contributions though :)

**Comment by theelfismike** [comment]
I spent a little time looking at this today, +1 - it looks like we're blocked until 2.0.0 gets published to Maven at the very least.

**Comment by traviswestbrook** [comment]
Seems to be working with gradle 2.11 and plugin 2.0.0-beta6

**Comment by theelfismike** [comment]
@traviswestbrook what version were you using? 1.1.0/1.2.0-SNAPSHOT/a custom build?

**Comment by traviswestbrook** [comment]
@theelfismike Custom build. Pretty much the build in #67 but using gradle 2.11.

**Comment by iordanis** [comment]
Anyone interested, we're planning to bring the fix in 1.2.0-SNAPSHOT today, test it for a bit and then release 1.2.0.

**Comment by theelfismike** [comment]
That's awesome! If you could let us know when the snapshot is pushed, we
can test as well.

Thanks!

**Comment by deepanshumadan** [comment]
Awesome!

**Comment by silviul** [comment]
The snapshot should be pushed. Try it.

**Comment by deepanshumadan** [comment]
Thanks! I don't see it, did you push it to Maven central?

**Comment by iordanis** [comment]
Check https://oss.sonatype.org/content/repositories/snapshots/com/shazam/fork/. Make sure you include the snapshot repo in your gradle file.

**Comment by deepanshumadan** [comment]
thanks, found it!

**Comment by ericjee** [comment]
coooool, thx @iordanis  @traviswestbrook , everything is working with new gradle 2.11 and 1.2.0-SNAPSHOT! :)

**Comment by deepanshumadan** [comment]
it works for us too! thanks @silviul @iordanis

**Comment by deepanshumadan** [comment]
@iordanis looks this bug is fixed, is there gonna be a 1.2.0 release soon?

**Comment by iordanis** [comment]
Yeah we'll release something tomorrow, since this was the last issue for this release. Thanks for confirming it worked.
